site_name: Haskell Tutorial
site_url: https://bibaijin.github.io/tutorial-haskell
site_description: Haskell 的学习心得
site_author: bibaijin

repo_url: https://github.com/bibaijin/tutorial-haskell

theme: mkdocs
theme_dir: 'custom_theme'

pages:
- 首页: index.md
- Haskell: haskell.md
- 关于: about.md

markdown_extensions:
    - smarty
    - sane_lists
    - footnotes
    - tables

copyright: Copyright &copy; 2015 <a href="mailto:bibaijin@gmail.com">金比白</a>.
